name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    if: ${{ (github.repository == 'darthcloud/BlueRetro') || (github.event_name == 'workflow_dispatch') }}
    strategy:
      matrix:
        hw_version: [hw1]
        br_config:
          [playstation]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/darthcloud/idf-blueretro:v5.5.0_2024-12-02
    outputs:
      br_version: ${{ env.br_version }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Build with ESP-IDF
      shell: bash
      run: |
        . $IDF_PATH/export.sh
        echo "br_version=$(git describe --always --tags --dirty)" >> $GITHUB_ENV
        rm -fr build
        echo "$(git describe --always --tags --dirty) ${{ matrix.hw_version }} ${{ matrix.br_config }}" | cut -c -31 > version.txt
        cat version.txt
        cp configs/${{ matrix.hw_version }}/${{ matrix.br_config }} sdkconfig
        BR_HW=_${{ matrix.hw_version }} BR_SYS=_${{ matrix.br_config }} idf.py reconfigure build
    - name: Copy OTA initial binary
      working-directory: ./build
      run: |
        mkdir ota
        mv ota_data_initial.bin ota/
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.hw_version }}_${{ matrix.br_config }}
        path: |
          build/partition_table/partition-table.bin
          build/bootloader/bootloader.bin
          build/ota/ota_data_initial.bin
          build/BlueRetro*.bin
        if-no-files-found: error
